<?php

$plugin = array(
  'title' => t('70-30 40-40-20'),
  'category' => t('Western'),
  'icon' => 'clean-70-30-40-40-20.png',
  'theme' => 'clean-70-30-40-40-20',
  'css' => '../../css/panel-layouts/clean-70-30-40-40-20.css',
  'regions' => array(
    'top_left' => t('Top left'),
    'top_right' => t('Top right'),
    'bottom_left' => t('Bottom left'),
    'bottom_middle' => t('Bottom middle'),
    'bottom_right' => t('Bottom right'),
    ),
  );
