<?php

$plugin = array(
  'title' => t('Clean Music'),
  'category' => t('Western'),
  'icon' => 'clean-music.png',
  'theme' => 'clean-music',
  'css' => '../../css/panel-layouts/clean-music.css',
  'regions' => array(
    'top_left' => t('Top left'),
    'top_right' => t('Top right'),
    'bottom_left' => t('Bottom left'),
    'bottom_middle' => t('Bottom middle'),
    'bottom_right' => t('Bottom right'),
    ),
  );
