<?php

// Plugin definition
$plugin = array(
  'title' => t('Clean Western Today'),
  'category' => t('Western'),
  'icon' => 'clean-westerntoday.png',
  'theme' => 'clean-westerntoday',
  'css' => '../../css/panel-layouts/clean-westerntoday.css',
  'regions' => array(
    'top_1' => t('100% Top First Area'),
    'top_2' => t('100% Top Second Area'),
    'left_1' => t('75% Left side top'),
    'right_1' => t('25% Right side top'),
    'left_2' => t('Left half column'),
    'mid_2' => t('Middle half column'),
    'right_2' => t('25% Right side bottom'),
    'col_1' => t('Column 1'),
    'col_2' => t('Column 2'),
    'col_3' => t('Column 3'),
    'col_4' => t('Column 4'),
    'bottom' => t('100% Bottom')
  ),
);
