<?php

// Plugin definition
$plugin = array(
  'title' => t('Clean Western Today'),
  'category' => t('Western'),
  'icon' => 'clean-westerntoday.png',
  'theme' => 'clean-westerntoday',
  'css' => '../../css/panel-layouts/clean-westerntoday.css',
  'regions' => array(
    'top' => t('100% Top'),
    'left' => t('75% Left side'),
    'right' => t('25% Right side'),
    'col_1' => t('Column 1'),
    'col_2' => t('Column 2'),
    'col_3' => t('Column 3'),
    'col_4' => t('Column 4'),
    'bottom' => t('100% Bottom')
  ),
);
