<?php

// Plugin definition
$plugin = array(
  'title' => t('Clean Huxley'),
  'category' => t('Western'),
  'icon' => 'clean-huxley.png',
  'theme' => 'clean-huxley',
  'css' => '../../css/panel-layouts/clean-huxley.css',
  'regions' => array(
    'left' => t('Left side'),
    'topright' => t('Top-right'),
    'bottomright' => t('Bottom-right'),
    'rightmidright' => t('Right middle-right'),
    'rightmidleft' => t('Right middle-left'),
  ),
);
