<?php

// Plugin definition
$plugin = array(
  'title' => t('Clean 54-46'),
  'category' => t('Western'),
  'icon' => 'clean-54-46.png',
  'theme' => 'clean-54-46',
  'css' => '../../css/panel-layouts/clean-54-46.css',
  'regions' => array(
    'left' => t('Left side'),
    'topright' => t('Top-right'),
    'bottomright' => t('Bottom-right'),
    'rightmidright' => t('Right middle-right'),
    'rightmidleft' => t('Right middle-left'),
  ),
);