<?php

$plugin = array(
  'title' => t('CFPA Department'),
  'category' => t('Western'),
  'icon' => 'cfpa-department.png',
  'theme' => 'cfpa-department',
  'css' => '../../css/panel-layouts/cfpa-department.css',
  'regions' => array(
    'top_left' => t('Top left'),
    'top_right' => t('Top right'),
    'bottom_left' => t('Bottom left'),
    'bottom_middle' => t('Bottom middle'),
    'bottom_right' => t('Bottom right'),
    ),
  );
