<?php

// Plugin definition
$plugin = array(
  'title' => t('100 50-50 33-33-33'),
  'category' => t('Western'),
  'icon' => '100--50-50--33-33-33.png',
  'theme' => '100--50-50--33-33-33',
  'css' => '../../css/panel-layouts/100--50-50--33-33-33.css',
  'regions' => array(
    'top' => t('Top'),
    'middle_left' => t('Middle Left'),
    'middle_right' => t('Middle Right'),
    'bottom_left' => t('Bottom Left'),
    'bottom_center' => t('Bottom Center'),
    'bottom_right' => t('Bottom Right')
  ),
);
