<?php

// Plugin definition
$plugin = array(
  'title' => t('50-50 33-33-33'),
  'category' => t('Western'),
  'icon' => '50-50--33-33-33.png',
  'theme' => '50-50--33-33-33',
  'css' => '../../css/panel-layouts/50-50--33-33-33.css',
  'regions' => array(
    'top_left' => t('Top Left'),
    'top_right' => t('Top Right'),
    'bottom_left' => t('Bottom Left'),
    'bottom_center' => t('Bottom Center'),
    'bottom_right' => t('Bottom Right')
  ),
);
